### ISSUE TITLE
[BUG] `inv add` returning error, not installing

### ISSUE THREAD

**Issue by Ben-Epstein** [anthonycorletti/python-project-template#11]
### To Reproduce

Run the following in a fresh dir
```
python -m venv .venv && source .venv/bin/activate
pip install snok
snok new myproj
inv add spacy
inv add fastapi
```

**Code that demonstrates the bug**:

```
inv add ...
```

### Expected behavior

Fastapi/spacy to be added to pyproject.toml and installed in my env

### Screenshots

<img width="413" alt="image" src="https://github.com/anthonycorletti/snok/assets/22605641/9330530b-6b84-45d9-b83a-310350909807">

### Environment

* python version [e.g. the output of `python --version`] 3.11.4
* OS: [e.g. Linux / Windows / macOS] macos
* snok version [e.g. 0.1.0] 0.0.7

### Additional context

:shipit:

**Comment by Ben-Epstein** [comment]
It looks like you need to run 
`inv add -p fastapi` or `inv add -p spacy`

Can you remove the requirement for `-p` in the command?

**Comment by anthonycorletti** [comment]
👋 will take a look!

**Comment by anthonycorletti** [comment]
made some fun changes in `0.0.9` that should address this 

let me know if that helps with setup & dependency management
