### ISSUE TITLE
[QUESTION] What is the `__token__` in the publish workflow 

### ISSUE THREAD

**Issue by Ben-Epstein** [anthonycorletti/python-project-template#7]
* [x] I used GitHub search to find a similar issue and didn't find what I was looking for.
* [x] I searched the available documentation for this project via integrated search.
* [x] I already searched in Google for what I was looking for and didn't find any information.

### Your question

What is this token, where exactly is it coming from, and how do I set it in my project? https://github.com/anthonycorletti/python-project-template/blob/main/.github/workflows/publish.yaml#L38

### Additional context

Currently I have to set my [`TWINE_USERNAME` as a secret](https://github.com/Ben-Epstein/spacy-to-hf/blob/main/.github/workflows/publish.yaml#L38) and use that, but I don't think that is the best practice. Can you add docs on how to set up the `__token__`?

**Comment by anthonycorletti** [comment]
It can be username that you set for your registry. I'll give an example for public `pypi`

Let's say I want to publish my package to pypi, after I've pushed for the first time, I can create an API token that I can use in CI.

<img width="1137" alt="Screenshot 2023-05-06 at 1 29 25 PM" src="https://user-images.githubusercontent.com/3477132/236638734-6c624708-aa8c-4174-9016-5a16bec415f0.png">

After you click add token, you'll be taken to a screen like so with all the details you need

<img width="1215" alt="Screenshot 2023-05-06 at 1 29 57 PM" src="https://user-images.githubusercontent.com/3477132/236638761-38e7f62a-09a5-49a1-9d5d-06d6c66ae7a0.png">

That should show you everything you need to know with relevant instructions.

**Comment by Ben-Epstein** [comment]
Thanks! That answers my question
